CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR NOT NULL,
	password VARCHAR NOT NULL
)

CREATE TABLE books (
	isbn INT PRIMARY KEY, 
	title VARCHAR NOT NULL, 
	author VARCHAR NOT NULL,
	year VARCHAR NOT NULL

)

CREATE TABLE reviews (
	id SERIAL PRIMARY KEY,
	user_id INT NOT NULL,
	book_isbn INT NOT NULL,
	rating INT NOT NULL,
	review_text VARCHAR NOT NULL
)
